### ISSUE TITLE
Update MemoryStore to Redis

### ISSUE THREAD

**Issue by Wkasel** [gosignal/dineforward#22]
In the current build we need to update the MemoryStore to an external one such as redis, just use the existing redis labs account?

```
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```

**Comment by Wkasel** [comment]
@mvachhar @mterrel -- what do you guys think?

**Comment by mterrel** [comment]
@Wkasel I think I figured out why you're seeing that message. I believe you said you saw it when you ran `yarn build`, but the fact that it's **build** not **start** didn't sink in when you said it.

So for build, using MemoryStore is currently intentional. The build process runs a Keystone instance, with `NODE_ENV=production`, allows Next.js to use it to get data for its build, then stops it. As far as I understand, MemoryStore should be totally sufficient for a short-lived, single instance of Keystone.

Let me know if you're seeing this message in another context besides `yarn build` or if you know of problems using MemoryStore in that limited situation.
